### PR TITLE
Supporting of Koa@2 was added

### PR DESCRIPTION
**Pull request by nervgh**
:smiley_cat:

### CODE REVIEW

**Comment by coderhaoxin** [comment]
cc @hallas

**Comment by nervgh** [comment]
What do you think about this PR?

**Comment by nervgh** [comment]
@coderhaoxin , @hallas Is there any chance that you will accept this PR? :smiley_cat:

**Comment by coderhaoxin** [comment]
@nervgh 
This PR is LGTM, but I can't publish new version on npm :)

ping @hallas

**Comment by hallas** [comment]
Hello @haoxins - should I add you to the package on npmjs?

I'm not going to be maintaining the package.

**Comment by hallas** [comment]
This way you can actually make this package compatible with new versions of Koa.

Ping @jonathanong 👋  I can also add you on npmjs.

**Comment by 3imed-jaberi** [comment]
@haoxins, plz close this PR

**Pull request closed without merging**
