### PR TITLE
Add esm entrypoint

### PR DESCRIPTION
**Pull request by Souler**

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@Souler Thanks for your contribution here, I will take care of this part due to publish the release quicker.

**Comment by Souler** [comment]
@3imed-jaberi  

Yea, this is what happens when you force push into a public branch. 

To be honest, I'm surprised and disapponted by your work ethic. You have effectevily removed my contributions from the history of this repo.

I'm not even going to comment on the fact that you made me remove the package lock file just to add it yourself right afterwards (because it is the correct thing to do).

**Comment by 3imed-jaberi** [comment]
@Souler I don't remove your work, I just squash your commits as you can see [here](https://github.com/koajs/accesslog/commit/642d935b43c0d32168c3b49385e82b5972565cd7). 


As I told you in my previous comment, we don't push the lock file but due to the usage of GH Action with the current configuration we need the lock file. So, I take the road to fix it immediately [here](https://github.com/koajs/accesslog/commit/93a177b7d794da5568c32536f1e11977a81555a3). Then some tests failed ([fix](https://github.com/koajs/accesslog/commit/38ab3993189656b17ff20ac67ea13fef02be3e66)) ...

**Comment by Souler** [comment]
@3imed-jaberi 

1. You [force-pushed](https://github.com/koajs/accesslog/activity) to a public repo; rewriting the history of commits **after** merging. That IS removing (and altering) my work for no good reason. If you consider yourself an OSS maintainer you should know that force pushing is **heavily** discouraged because you negatively affect downstream forks. However, I'm happy you are still top contributor to the repo (I cant really imagine any other reason why you would do that).
2. Regarding the package-lock.json; it's almost like you could have re-considered **before** merging after being linked [official documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#description:~:text=This%20file%20is%20intended%20to%20be%20committed%20into%20source%20repositories) on the matter or even deciding to mirror the behavior of the "root" package of this org (i.e: [koa](https://github.com/koajs/accesslog/blob/master/package-lock.json)). Including lockfiles in version control is an **industry standard**. Not doing it is negligent on several aspects: security and developer experience.
3. Because you saw red on the CI, you panicked decided to fix a failing test in a way that will cause it to fail on any developer machine that is not configured as UTC. I was about to open a PR to address it after seeing it; but I'll leave you to it.

I was **super motivated** to keep contributing to this repo or the org overall; but seeing this treatment I'm 100% not going to do so. I really hope you eventually understand why what you did is just plain wrong.

**Pull request closed without merging**
